spring.application.name=webchamados-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/chamados_db
spring.datasource.username=webchamados
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080